name: Deploy to GitHub Pages from chosen branch

on:
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        with: 
          ref: ${{ github.ref_name }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.17.1  # or whatever version your project uses

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          npm exec gh-pages -- \
            -d build \
            -r https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
